#!/usr/bin/env python3
"""Regenerate the index tables at the top of the project-context registries.

`DECISIONS.md` and `LEARNINGS.md` grow without bound and are read end to end.
An agent asking "does anything here constrain what I am about to do?" pays the
whole file to find the two entries that matter. These indexes answer that
question first.

The index is *generated*, never hand-maintained: a hand-written one drifts
within a few commits, and a stale index is worse than none because it is
trusted. Anything between the markers is replaced from the entries themselves,
so the index cannot disagree with them.

    python3 context_index.py --context project-context           # rewrite
    python3 context_index.py --context project-context --check   # exit 1 if stale
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

START = "<!-- context-index:start -->"
END = "<!-- context-index:end -->"

REGISTRIES = (
    {
        "file": "DECISIONS.md",
        "prefix": "D",
        "columns": ("Decision", "Status"),
        "field": "Status",
        "default": "`accepted`",
        "blurb": "Index — generated by `context_index.py`; do not hand-edit.",
    },
    {
        "file": "LEARNINGS.md",
        "prefix": "L",
        "columns": ("Learning", "Applies to"),
        "field": "Scope",
        "default": "—",
        "blurb": (
            "Index — generated by `context_index.py`; do not hand-edit.\n"
            "Open the entries this index puts in scope rather than reading the\n"
            "registry end to end."
        ),
    },
)


def slug(title: str) -> str:
    """GitHub heading anchor for a heading.

    GitHub *strips* punctuation rather than hyphenating it, so the backticks
    and apostrophes that entry headings tend to carry disappear entirely — a
    slugifier that replaces them with hyphens produces links that silently do
    not land. Underscores are word characters and survive.
    """
    cleaned = re.sub(r"[^\w\s-]", "", title.lower())
    return re.sub(r"\s+", "-", cleaned.strip())


def entries(text: str, prefix: str) -> list[tuple[str, str, str, str]]:
    found: list[tuple[str, str, str, str]] = []
    heads = list(re.finditer(r"^## (%s-\d+): (.+)$" % prefix, text, re.M))
    for index, match in enumerate(heads):
        end = heads[index + 1].start() if index + 1 < len(heads) else len(text)
        body = text[match.end():end]

        def field(name: str) -> str:
            hit = re.search(r"^- %s:\s*(.+?)(?=\n- |\n\n|\Z)" % name, body, re.M | re.S)
            return " ".join(hit.group(1).split()) if hit else ""

        found.append((match.group(1), match.group(2).strip(), field("Status"), field("Scope")))
    return found


def render(text: str, spec: dict) -> str:
    lines = [
        START,
        spec["blurb"],
        "",
        f"| ID | {spec['columns'][0]} | {spec['columns'][1]} |",
        "| --- | --- | --- |",
    ]
    for ident, title, status, scope in entries(text, spec["prefix"]):
        value = (status if spec["field"] == "Status" else scope) or spec["default"]
        lines.append(f"| [`{ident}`](#{slug(ident + ' ' + title)}) | {title} | {value} |")
    lines.append(END)
    return "\n".join(lines)


def rebuild(text: str, spec: dict) -> str:
    block = render(text, spec)
    first = re.search(r"^## ", text, re.M)
    if not first:
        return text
    head, rest = text[:first.start()], text[first.start():]

    # Discard any previous index before rebuilding — a marked block, an
    # unmarked one left by an earlier generation, or both. Stripping only the
    # prose blurb would leave its table behind and silently duplicate the
    # index, so the table rows go too. Only prose above the first entry is kept,
    # which makes this self-healing rather than order-dependent.
    if START in head and END in head:
        head = head[:head.index(START)] + head[head.index(END) + len(END):]
    kept = [
        line for line in head.splitlines()
        if not line.startswith("|") and not line.startswith("Index —")
    ]
    head = re.sub(r"\n{3,}", "\n\n", "\n".join(kept)).rstrip("\n")
    return head + "\n\n" + block + "\n\n" + rest


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report staleness instead of writing")
    parser.add_argument("--context", default="project-context", help="path to the project-context directory")
    args = parser.parse_args(argv)

    context = Path(args.context)
    stale: list[str] = []
    for spec in REGISTRIES:
        path = context / spec["file"]
        if not path.is_file():
            print(f"missing: {path}", file=sys.stderr)
            continue
        current = path.read_text(encoding="utf-8")
        updated = rebuild(current, spec)
        count = len(entries(current, spec["prefix"]))
        if current == updated:
            print(f"{spec['file']}: current ({count} entries)")
            continue
        stale.append(spec["file"])
        if args.check:
            print(f"{spec['file']}: STALE ({count} entries)")
        else:
            path.write_text(updated, encoding="utf-8")
            print(f"{spec['file']}: regenerated ({count} entries)")

    if args.check and stale:
        print("\nIndex is stale. Run: python3 context_index.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
