from __future__ import annotations

from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "skills" / "project-context" / "scripts" / "context_index.py"

DECISIONS = """# Decision Registry

Prose that must survive regeneration.

## D-001: Use `pnpm` for the workspace's package manager

- Status: `accepted`
- Statement: The repository standardises on pnpm.

## D-002: Don't ship a bundled runtime

- Status: `superseded`
- Statement: No bundled runtime.
"""

LEARNINGS = """# Learning Registry

## L-001: Watchers miss renames on case-insensitive volumes

- Scope: build tooling
- Evidence: observed on macOS.
"""


class IndexTests(unittest.TestCase):
    def context(self, stack) -> Path:
        directory = Path(stack.enter_context(tempfile.TemporaryDirectory()))
        context = directory / "project-context"
        context.mkdir()
        (context / "DECISIONS.md").write_text(DECISIONS, encoding="utf-8")
        (context / "LEARNINGS.md").write_text(LEARNINGS, encoding="utf-8")
        return context

    def run_index(self, context: Path, *args: str, expected: int = 0):
        result = subprocess.run(
            [sys.executable, str(SCRIPT), "--context", str(context), *args],
            check=False, capture_output=True, text=True,
        )
        self.assertEqual(expected, result.returncode, result.stderr or result.stdout)
        return result

    def test_index_is_generated_with_github_compatible_anchors(self) -> None:
        """GitHub strips backticks and apostrophes rather than hyphenating them.

        A slugifier that replaces them produces links that silently do not land.
        """
        import contextlib

        with contextlib.ExitStack() as stack:
            context = self.context(stack)
            self.run_index(context)
            text = (context / "DECISIONS.md").read_text(encoding="utf-8")
            self.assertIn("<!-- context-index:start -->", text)
            self.assertIn("#d-001-use-pnpm-for-the-workspaces-package-manager", text)
            self.assertIn("#d-002-dont-ship-a-bundled-runtime", text)
            self.assertIn("| `accepted` |", text)
            self.assertIn("| `superseded` |", text)
            self.assertIn("Prose that must survive regeneration.", text)
            learnings = (context / "LEARNINGS.md").read_text(encoding="utf-8")
            self.assertIn("| build tooling |", learnings)

    def test_regeneration_is_idempotent_and_check_reports_staleness(self) -> None:
        import contextlib

        with contextlib.ExitStack() as stack:
            context = self.context(stack)
            self.run_index(context)
            first = (context / "DECISIONS.md").read_text(encoding="utf-8")
            self.run_index(context)
            self.assertEqual(first, (context / "DECISIONS.md").read_text(encoding="utf-8"))
            self.run_index(context, "--check")

            path = context / "DECISIONS.md"
            path.write_text(
                path.read_text(encoding="utf-8")
                + "\n## D-003: Pin the toolchain\n\n- Status: `accepted`\n",
                encoding="utf-8",
            )
            self.run_index(context, "--check", expected=1)
            self.run_index(context)
            self.run_index(context, "--check")

    def test_an_earlier_unmarked_index_is_replaced_not_duplicated(self) -> None:
        """Stripping only the prose blurb leaves its table behind.

        The result is two indexes, one of them stale — and stale rows read as
        authoritative.
        """
        import contextlib

        with contextlib.ExitStack() as stack:
            context = self.context(stack)
            path = context / "DECISIONS.md"
            text = path.read_text(encoding="utf-8")
            head, rest = text.split("## D-001", 1)
            legacy = (
                "Index — generated by an earlier version; do not hand-edit.\n\n"
                "| ID | Decision | Status |\n| --- | --- | --- |\n"
                "| [`D-999`](#gone) | An entry that no longer exists | `accepted` |\n\n"
            )
            path.write_text(head + legacy + "## D-001" + rest, encoding="utf-8")

            self.run_index(context)
            rebuilt = path.read_text(encoding="utf-8")
            self.assertEqual(1, rebuilt.count("| ID | Decision | Status |"))
            self.assertNotIn("D-999", rebuilt)
            self.assertIn("Prose that must survive regeneration.", rebuilt)


if __name__ == "__main__":
    unittest.main()
